package com.dailycodebuffer.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.aop.aspectj.DeclareParentsAdvisor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "employee")
public class Employee {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    private String employeeid;
    @DynamoDBAttribute
    private String firstName;

    @DynamoDBAttribute
    private String lastName;
    @DynamoDBAttribute
    private String emailId;
    @DynamoDBAttribute
    private Department department;

}
